---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: default
  labels:
    knative.dev/type: app
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/petee/helloworld-nodejs
            env:
            - name: TARGET
              value: "rev5"
